// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvputialcmqkzfiyyphw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2cHV0aWFsY21xa3pmaXl5cGh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3MjExMzAsImV4cCI6MjA3MzI5NzEzMH0.hN32NdsTDYbaIujtZSrogljkwnv5IFM-FdOh32ERJBs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});